{% set name = "executing" %}
{% set version = "2.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5d108c028108fe2551d1a7b2e8b713341e2cb4fc0aa7dcf966fa4327a5226755

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}

test:
  imports:
    - executing
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/executing
  summary: Get the currently executing AST node of a frame, and other information
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/alexmojaki/executing

extra:
  recipe-maintainers:
    - alexmojaki
    - anthchirp
