{% set name = "executing" %}
{% set version = "0.8.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c6554e21c6b060590a6d3be4b82fb78f8f0194d809de5ea7df1c093763311501

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
    - setuptools
    - setuptools_scm
  run:
    - python >=2.7

test:
  imports:
    - executing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/executing
  summary: Get the currently executing AST node of a frame, and other information
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/alexmojaki/executing

extra:
  recipe-maintainers:
    - alexmojaki
    - anthchirp
